version: '3.9'
services:
  app:
    extends: 
      file: docker-compose.common.yml
      service: app
    depends_on:
      - postgresdb
    environment:
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_TYPE=postgres

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=postgresdb
    ports:
      - '5432:5432'
    networks:
      - learning
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

networks:
  learning:
    driver: bridge