version: '3.9'
services:
  app:
    container_name: todo_server_container
    env_file:
      - .env
    build: .
    ports:
      - 9090:9090
    restart: on-failure
    networks:
      - learning
    healthcheck:
      test: /app/health
      interval: 60s
      retries: 5
      timeout: 5s
      start_period: 10s
